name: Build MAUI Android (.NET 10 - Manual)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore SnapDoc.sln

      - name: Decode and save keystore
        shell: pwsh
        run: |
          [System.IO.File]::WriteAllBytes("SnapDoc.keystore", [Convert]::FromBase64String($env:ANDROID_KEYSTORE_BASE64))

      - name: Build Android App (Release)
        shell: pwsh
        run: |
          dotnet publish SnapDoc/SnapDoc.csproj -c Release -f net10.0-android `
            /p:AndroidKeyStore=true `
            /p:AndroidKeyAlias=$env:ANDROID_KEY_ALIAS `
            /p:AndroidKeyPassword=$env:ANDROID_KEY_PASSWORD `
            /p:AndroidStorePassword=$env:ANDROID_KEYSTORE_PASSWORD `
            /p:AndroidKeyStorePath=SnapDoc.keystore `
            /p:AndroidPackageFormat=aab

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidApp
          path: |
            **/bin/Release/net10.0-android/**/*.aab
            **/bin/Release/net10.0-android/**/*.apk
